<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="WireMock.Net" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RagAgent.Api\RagAgent.Api.csproj" />
    <ProjectReference Include="..\RagAgent.HackerNews\RagAgent.HackerNews.csproj" />
    <ProjectReference Include="..\RagAgent.Agents\RagAgent.Agents.csproj" />
    <ProjectReference Include="..\RagAgent.Core\RagAgent.Core.csproj" />
    <ProjectReference Include="..\RagAgent.InMemory\RagAgent.InMemory.csproj" />
  </ItemGroup>

</Project>
