<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.Agents.AI.Workflows" />
    <PackageReference Include="AWSSDK.Extensions.Bedrock.MEAI" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.AI.Evaluation.Quality" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="AWSSDK.BedrockRuntime" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RagAgent.Core\RagAgent.Core.csproj" />
  </ItemGroup>

</Project>
