<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Testcontainers.Qdrant" />
    <PackageReference Include="Testcontainers.Redis" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RagAgent.Api\RagAgent.Api.csproj" />
    <ProjectReference Include="..\RagAgent.Agents\RagAgent.Agents.csproj" />
    <ProjectReference Include="..\RagAgent.Qdrant\RagAgent.Qdrant.csproj" />
    <ProjectReference Include="..\RagAgent.Redis\RagAgent.Redis.csproj" />
    <ProjectReference Include="..\RagAgent.Core\RagAgent.Core.csproj" />
  </ItemGroup>

</Project>
